### ISSUE TITLE
Product Single Pages: Bulleted lists in the single pages don't use the blue bullets shown in the About Us page

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Traffic-System-West#37]
http://trafficsystemswest.stage.titanweb.com.au/products/traffic-calming/traffic-calming-speed-cushions-innovative-safety-solution-2/

**Comment by arielcebudigital** [comment]
Please provide screenshot, working in our end

**Comment by bernardtitan** [comment]
![mfkr](https://cloud.githubusercontent.com/assets/11186359/7199467/8d9c59a2-e527-11e4-8342-399e075348b7.jpg)

**Comment by arielcebudigital** [comment]
![product-single](https://cloud.githubusercontent.com/assets/11186408/7222269/3855d474-e73d-11e4-81a4-6750c74aa81e.jpg)

Be specific in your Bug Issues...

**Comment by arielcebudigital** [comment]
The one who add the content used <p> instead of <ul><li>, Using <ul><li> will change the format of list content...
