### ISSUE TITLE
Product Single Pages: When the user attaches a PDF file, the file icon should be displayed to its left and the file size should be displayed to its right.

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Traffic-System-West#40]
http://trafficsystemswest.stage.titanweb.com.au/products/roadmarking/cold-applied-plastic/

**Comment by arielcebudigital** [comment]
I just follow the old site since they want to remain the layout, 
FROM jolene: they only want the site to be responsive.

**Comment by bernardtitan** [comment]
The image is still missing in the site regardless, fix it
