### ISSUE TITLE
Products -> Flexible Signage -> Signs: The 'Flexi-Tuff Street Sign Hinge' header is incomplete. Refer to the original site.

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Traffic-System-West#41]

**Comment by arielcebudigital** [comment]
Product Page - All Products contents and categories where posted by Hanrie (https://projects.titanweb.com.au/public/index.php?path_info=projects/traffic-systems-west-pack1responsive-/tasks/26)
