### ISSUE TITLE
General - Gallery: The NGGallery extended albums aren't styled properly, the bordered container is too wide

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Traffic-System-West#59]
http://trafficsystemswest.stage.titanweb.com.au/about-us/

**Comment by arielcebudigital** [comment]
Default style of extended album have full width borders, This is standard of ngg-gallery extend.

**Comment by bernardtitan** [comment]
Doesn't matter if it's the default, it doesn't look right

**Comment by arielcebudigital** [comment]
Leoman: suggested to remove the border and change the size.
