### ISSUE TITLE
Banner: The banner no longer rotates

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Traffic-System-West#62]

**Comment by arielcebudigital** [comment]
The banner does not rotate when it has only 1 featured image..

**Comment by bernardtitan** [comment]
Bug caused by the removal of banners in https://github.com/titan-cebu/Traffic-System-West/issues/44

Replace the banner images as was promised in the previous ticket

**Comment by bernardtitan** [comment]
This particular banner image will be removed at the end of the QA process, current banners should be replaced
